In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
pd.set_option('display.max_rows', None)

In [2]:
# read in the salary data and see the inconsistencies made from the damn pdf parser

In [3]:
df = pd.read_csv('../output/salaries.csv')

In [4]:
df.head()

,year,club,last_name,first_name,position,base_salary,guaranteed_comp
0,2025,Atlanta United,Miranchuk,Aleksey,ATTACKING MIDFIELD,3600000.0,4885441.0
1,2025,Atlanta United,Latte Lath,Emmanuel,CENTER FORWARD,3534546.0,4030546.0
2,2025,Atlanta United,Thiaré,Jamal,CENTER FORWARD,700000.0,730000.0
3,2025,Atlanta United,Togashi,Cayman,CENTER FORWARD,104000.0,104000.0
4,2025,Atlanta United,Mihaj,Enea,CENTER-BACK,1030000.0,1372000.0

In [5]:
df.shape # dang, 11k rows

(11661, 7)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11661 entries, 0 to 11660
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   year             11661 non-null  int64
 1   club             11548 non-null  object
 2   last_name        11551 non-null  object
 3   first_name       11498 non-null  object
 4   position         10584 non-null  object
 5   base_salary      11661 non-null  float64
 6   guaranteed_comp  11661 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 637.8+ KB

In [7]:
# alright so we are already in trouble
# things that went right:
# - data types are correct
# things that went wrong:
# - null values belonging to club, lastname, firstname, position

In [8]:
# let's analyze this to see the problem
missing_values_df = df[df.isna().any(axis=1)]

In [9]:
missing_values_df.shape

(1133, 7)

In [10]:
# split by year to handle each one
years_split_dict = {year: group for year, group in missing_values_df.groupby('year')}

In [11]:
years_split_dict.keys()

dict_keys([2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2020, 2021, 2022, 2023, 2024])

In [12]:
missing_values_df.year.value_counts()

year
2024    910
2023     30
2018     23
2015     18
2017     17
2016     17
2022     17
2014     17
2013     13
2012     13
2021     11
2011     10
2010     10
2020      7
2009      7
2008      7
2007      6
Name: count, dtype: int64

In [13]:
# this function represents the cleanse of each group in missing_values_df
def cleanse_null_values(data):
    # main_df should be the main dataframe
    _missing_values_df = df[df.isna().any(axis=1)]
    print(f"there are {_missing_values_df.shape[0]} rows containing null values")
    _years_split_dict = {year: group for year, group in missing_values_df.groupby('year')}
    print(f"there are null values found within each of these years: {_years_split_dict.keys()}")
    # --- YEAR 2007 ---
    current_year_analyzing = 2007
    current_year_df = _years_split_dict[current_year_analyzing]
    data.drop(index=years_split_dict[current_year_analyzing].index, inplace=True)
    
    # --- YEAR 2008 ---
    current_year_analyzing = 2008
    current_year_df = _years_split_dict[current_year_analyzing]
    
    # --- YEAR 2009 ---
    current_year_analyzing = 2009
    current_year_df = _years_split_dict[current_year_analyzing]
    
    # --- YEAR 2010 ---
    current_year_analyzing = 2010
    current_year_df = _years_split_dict[current_year_analyzing]
    
    # --- YEAR 2011 ---
    current_year_analyzing = 2011
    current_year_df = _years_split_dict[current_year_analyzing]
    
    # --- YEAR 2012 ---
    current_year_analyzing = 2012
    current_year_df = _years_split_dict[current_year_analyzing]
    
    # --- YEAR 2013 ---
    current_year_analyzing = 2013
    current_year_df = _years_split_dict[current_year_analyzing]
    
    # --- YEAR 2014 ---
    current_year_analyzing = 2014
    current_year_df = _years_split_dict[current_year_analyzing]
    
    # --- YEAR 2015 ---
    current_year_analyzing = 2015
    current_year_df = _years_split_dict[current_year_analyzing]
    
    # --- YEAR 2016 ---
    current_year_analyzing = 2016
    current_year_df = _years_split_dict[current_year_analyzing]
    
    # --- YEAR 2017 ---
    current_year_analyzing = 2017
    current_year_df = _years_split_dict[current_year_analyzing]
    
    # --- YEAR 2018 ---
    current_year_analyzing = 2018
    current_year_df = _years_split_dict[current_year_analyzing]

    # --- YEAR 2019 ---
    # current_year_analyzing = 2019
    # current_year_df = _years_split_dict[current_year_analyzing]
    
    # --- YEAR 2020 ---
    current_year_analyzing = 2020
    current_year_df = _years_split_dict[current_year_analyzing]
    
    # --- YEAR 2021 ---
    current_year_analyzing = 2021
    current_year_df = _years_split_dict[current_year_analyzing]
    
    # --- YEAR 2022 ---
    current_year_analyzing = 2022
    current_year_df = _years_split_dict[current_year_analyzing]
    
    # --- YEAR 2023 ---
    current_year_analyzing = 2023
    current_year_df = _years_split_dict[current_year_analyzing]
    
    # --- YEAR 2024 ---
    current_year_analyzing = 2024
    current_year_df = _years_split_dict[current_year_analyzing]
    
    return data

In [14]:
# testing the function as we go
print(df.shape)
new_df = cleanse_null_values(data=df.copy())
print(new_df.shape)
print(df.shape)

(11661, 7)
there are 1133 rows
there are null values found within each of these years: dict_keys([2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2020, 2021, 2022, 2023, 2024])

KeyError: 2019

# missing data for 2019

---

In [23]:
# okay now lets analyze year one by one to see what is wrong

analyzing year 2007

In [50]:
year_analyzing = 2007

In [51]:
years_split_dict[2007] # okay at first glance, these positions in 2007 are empty and their base salary and guranteed comp is the same year as well so I believr we can safely cut this after verification

       year club last_name first_name position  base_salary  guaranteed_comp
11337  2007  NaN       NaN        NaN      NaN       2007.0           2007.0
11391  2007  NaN       NaN        NaN      NaN       2007.0           2007.0
11445  2007  NaN       NaN        NaN      NaN       2007.0           2007.0
11499  2007  NaN       NaN        NaN      NaN       2007.0           2007.0
11553  2007  NaN       NaN        NaN      NaN       2007.0           2007.0
11607  2007  NaN       NaN        NaN      NaN       2007.0           2007.0

In [53]:
dropped_07_vals = df.drop(index=years_split_dict[year_analyzing].index)

In [54]:
dropped_07_vals.shape

(11655, 7)

In [55]:
# verification
dropped_07_vals.loc[dropped_07_vals['year'] == year_analyzing].isna().any(axis=1).value_counts()

False    371
Name: count, dtype: int64